name: Test

on:
  push:
    branches: [ feat/test ]
  pull_request:
    branches: [ feat/test ]

jobs:
  build:
    name: Tests
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install fastlane
        run: |
          brew install fastlane

      - name: Run Tests
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          fastlane tests